mittprogram: mitt_program.c konstanter.o
	gcc -o mittprogram mitt_program.c konstanter.o

konstanter.o: konstanter.c
	gcc -c konstanter.c


# Körs genom att skriva först make mittprogram och sedan ./mittprogram
